version: '3.8'
services:
  api:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env.production
    depends_on:
      - mongo
      - postgres
      - redis

  mongo:
    image: mongo:7

  postgres:
    image: postgres:15

  redis:
    image: redis:latest
