// Redux action types for notification management
export const NOTIFICATIONS_LOADING = 'NOTIFICATIONS_LOADING';
export const NOTIFICATIONS_SUCCESS = 'NOTIFICATIONS_SUCCESS';
export const NOTIFICATIONS_FAILURE = 'NOTIFICATIONS_FAILURE';

export const UNREAD_COUNT_LOADING = 'UNREAD_COUNT_LOADING';
export const UNREAD_COUNT_SUCCESS = 'UNREAD_COUNT_SUCCESS';
export const UNREAD_COUNT_FAILURE = 'UNREAD_COUNT_FAILURE';

export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';
export const NOTIFICATION_MARK_READ = 'NOTIFICATION_MARK_READ';
export const NOTIFICATION_DELETE = 'NOTIFICATION_DELETE';
export const NOTIFICATIONS_MARK_ALL_READ = 'NOTIFICATIONS_MARK_ALL_READ';

export const SSE_CONNECTION_STATUS = 'SSE_CONNECTION_STATUS';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';
